site_name: LOAF
site_description: Local Observations and Atmospheric Forecasting
site_url: https://pandoroml.github.io/LOAF/

repo_url: https://github.com/PandoroML/LOAF

extra:
  social:
    - icon: fontawesome/solid/rss
      link: /feed_rss_created.xml
      name: RSS Feed

theme:
  name: material
  palette:
    primary: amber
    accent: teal
  features:
    - navigation.footer

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  - blog:
      blog_dir: dev-log
      blog_toc: true
      post_date_format: long
  - rss:
      match_path: "dev-log/posts/.*"
      date_from_meta:
        as_creation: date

nav:
  - Home: index.md
  - Dev Log: dev-log/index.md
