site_name: LOAF

repo_url: https://github.com/PandoroML/LOAF

theme:
  name: material
  palette:
    primary: amber
    accent: teal
  features:
    - navigation.footer

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  - blog:
      blog_dir: dev-log
      blog_toc: true
      post_date_format: long

nav:
  - Home: index.md
  - Dev Log: dev-log/
