site_name: LOAF

repo_url: https://github.com/PandoroML/LOAF

theme:
  name: material

  features:
    - navigation.footer

plugins:
  - search
  - blog:
      blog_dir: dev-log
      blog_toc: true
      post_date_format: long

nav:
  - Home: index.md
  - Dev Log: dev-log/
