[project]
name = "LOAF"
version = "0.1.0"
description = "Local Observations and Atmospheric Forecasting"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mkdocs-material>=9.7.1",
    "mkdocs-rss-plugin>=1.17.1",
]
